name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "coinbaseback/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env: # tu secret de JWT
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDGRID_SENDER: ${{ secrets.SENDGRID_SENDER }}
      NODE_ENV: test # importante para que se use el schema test y SQLite

    defaults:
      run:
        working-directory: coinbaseback # siempre corre dentro de coinbaseback

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: coinbaseback/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Prisma Generate
        run: npx prisma generate --schema=prisma/schema.test.prisma

      - name: Push Prisma schema to SQLite
        run: npx prisma db push --schema=prisma/schema.test.prisma

      - name: Run tests
        run: npx vitest run
